PUT http://localhost:60001/sync/in/pod
Content-Type: application/json

{
    "artifact": "nginx/nginx-dev",
    "container": "nginx",
    "path": "to/path"
}

###

PUT http://localhost:60001/sync/in/allPods
Content-Type: application/json

{
    "path": "to/path"
}
